### ISSUE TITLE
Crashing solver example

### ISSUE THREAD

**Issue by balasub** [VUISIS/formula#12]
The following input causes a crash when run with the command below.

Input:

domain Mapping
{
  Component ::= new (id: Integer, utilization: Real).
  Processor ::= new (id: Integer).
  Mapping   ::= new (c: Component, p: Processor).

  // The utilization must be > 0
  invalidUtilization :- c is Component, c.utilization <= 0.

  badMapping :- p is Processor,
        s = sum(0.0, { c.utilization |
                   c is Component, Mapping(c, p) }), s > 100.

  conforms no badMapping.
}

model m of Mapping
{
  c1 is Component(0, 10).
  c2 is Component(1, 90).
  p1 is Processor(0).
  Mapping(c1, p1).
  Mapping(c2, p1).
}

partial model pm of Mapping
{
  c1 is Component(0, x).
  c2 is Component(1, y).
  p1 is Processor(0).
  Mapping(c1, p1).
  Mapping(c2, p1).
}

Command:

solve pm 1 invalidUtilization, Component(0, x), x > -30, x < -25

Stack trace:

Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Formula.Common.Rules.CoreRule.GroundNode.<>c__DisplayClass7_0.<TryEval>b__1(Term x, IEnumerable`1 ch, SuccessToken s) in /Users/daniel/work/formula/formula/Src/Core/Common/Rules/CoreRule.cs:line 2913
   at Microsoft.Formula.Common.Terms.Term.Compute[S](Func`3 unfold, Func`4 fold, SuccessToken token) in /Users/daniel/work/formula/formula/Src/Core/Common/Terms/Term.cs:line 340
   at Microsoft.Formula.Common.Rules.CoreRule.GroundNode.TryEval(SymExecuter facts, Int32 bindingLevel) in /Users/daniel/work/formula/formula/Src/Core/Common/Rules/CoreRule.cs:line 2882
   at Microsoft.Formula.Common.Rules.CoreRule.Initialize(SymExecuter facts) in /Users/daniel/work/formula/formula/Src/Core/Common/Rules/CoreRule.cs:line 1643
   at Microsoft.Formula.Common.Rules.CoreRule.Execute(Term binding, Int32 findNumber, SymExecuter index, Boolean keepDerivations, Map`2 pending) in /Users/daniel/work/formula/formula/Src/Core/Common/Rules/CoreRule.cs:line 729
   at Microsoft.Formula.Solver.SymExecuter.Execute() in /Users/daniel/work/formula/formula/Src/Core/Solver/Execution/SymExecuter.cs:line 635
   at Microsoft.Formula.Solver.SymExecuter.Solve() in /Users/daniel/work/formula/formula/Src/Core/Solver/Execution/SymExecuter.cs:line 387
   at Microsoft.Formula.Solver.Solver.Solve() in /Users/daniel/work/formula/formula/Src/Core/Solver/Solver.cs:line 309
   at Microsoft.Formula.API.SolveResult.Start() in /Users/daniel/work/formula/formula/Src/Core/API/Results/SolveResult.cs:line 89
   at Microsoft.Formula.API.Env.<>c__DisplayClass36_0.<Solve>b__0() in /Users/daniel/work/formula/formula/Src/Core/API/Base/Env.cs:line 1194
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Formula.CommandLine.TaskManager.TaskData.get_Duration() in /Users/daniel/work/formula/formula/Src/CommandLine/TaskManager.cs:line 247
   at Microsoft.Formula.CommandLine.TaskManager.MkTaskTable(List`1& rows, Int32[]& colWidths) in /Users/daniel/work/formula/formula/Src/CommandLine/TaskManager.cs:line 173
   at Microsoft.Formula.CommandLine.CommandInterface.DoLS(String s) in /Users/daniel/work/formula/formula/Src/CommandLine/CommandInterface.cs:line 2265
   at Microsoft.Formula.CommandLine.CommandInterface.DoCommandLocked(String command) in /Users/daniel/work/formula/formula/Src/CommandLine/CommandInterface.cs:line 457
   at Microsoft.Formula.CommandLine.CommandInterface.DoCommand(String command) in /Users/daniel/work/formula/formula/Src/CommandLine/CommandInterface.cs:line 343
   at Microsoft.Formula.CommandLine.InteractivePrompt.Run(CommandInterface ci) in /Users/daniel/work/formula/formula/Src/CommandLine/InteractivePrompt.cs:line 408
   at Microsoft.Formula.CommandLine.CommandLineProgram.Main(String[] args) in /Users/daniel/work/formula/formula/Src/CommandLine/CommandLineProgram.cs:line 35
zsh: abort      dotnet bin/Debug/MacOS/x64/net6.0/CommandLine.dll

**Comment by balasub** [comment]
Fixed in 788764229bbc893638bc580e95f7df2eb15a88f8
